class Default:
    left_top = '┌'
    right_top = '┐'
    left_bottom = '└'
    right_bottom = '┘'
    horizontal = '─'
    vertical = '│'
    cross = '┼'
    cross_top = '┬'
    cross_bottom = '┴'
    cross_left = '├'
    cross_right = '┤'
    dashed_horizontal = '┄'
    dashed_vertical = '┆'
    empty = ' '

class Bold(Default):
    left_top = '┏'
    right_top = '┓'
    left_bottom = '┗'
    right_bottom = '┛'
    horizontal = '━'
    vertical = '┃'
    cross = '╋'
    cross_top = '┫'
    cross_bottom = '┣'
    cross_left = '┳'
    cross_right = '┻'
    dashed_horizontal = '┅'
    dashed_vertical = '┆'

class Double(Default):
    left_top = '╔'
    right_top = '╗'
    left_bottom = '╚'
    right_bottom = '╝'
    horizontal = '═'
    vertical = '║'
    cross = '╬'
    cross_top = '╦'
    cross_bottom = '╩'
    cross_left = '╠'
    cross_right = '╣'

class Circle(Default):
    left_top = '╭'
    right_top = '╮'
    left_bottom = '╰'
    right_bottom = '╯'

class LeagcyASCIICode(Default):
    left_top = '+'
    right_top = '+'
    left_bottom = '+'
    right_bottom = '+'
    horizontal = '-'
    vertical = '|'
    cross = '+'
    cross_top = '+'
    cross_bottom = '+'
    cross_left = '+'
    cross_right = '+'

class BoldHorizontal(Default):
    left_top = '┍'
    right_top = '┑'
    left_bottom = '┕'
    right_bottom = '┙'
    horizontal = '━'
    cross = '┿'
    cross_left = '┝'
    cross_right = '┥'
    cross_top = '┯'
    cross_bottom = '┷'
    dashed_horizontal = '┅'

class BoldVertical(Default):
    left_top = '┎'
    right_top = '┒'
    left_bottom = '┖'
    right_bottom = '┚'
    vertical = '┃'
    cross = '┱'
    cross_top = '┰'
    cross_bottom = '┲'
    cross_left = '┫'
    cross_right = '┣'
    dashed_horizontal = '┅'

class DoubleHorizontal(Default):
    left_top = '╒'
    right_top = '╕'
    left_bottom = '╘'
    right_bottom = '╛'
    horizontal = '═'
    cross = '╤'
    cross_left = '╞'
    cross_right = '╡'
    cross_top = '╪'
    cross_bottom = '╧'

class DoubleVertical(Default):
    left_top = '╓'
    right_top = '╖'
    left_bottom = '╙'
    right_bottom = '╜'
    vertical = '║'
    cross = '╪'
    cross_top = '╥'
    cross_bottom = '╨'
    cross_left = '╖'
    cross_right = '╜'

